import com.vub.model.Entry;

dialect "java" 


global HardSoftScoreHolder scoreHolder;

// Rule: sameStartDateCourse
rule "sameStartDateCourse"
	when 
		Entry($startDate : startDate)
		Entry(
	then
		scoreHolder.addConstraintMatch(kcontext, -1);

end



// Rule RoomCapacity: For each lecture, the number of students that attend the course must be less or equal
// than the number of seats of all the rooms that host its lectures.
// Each student above the capacity counts as 1 point of penalty.
// rule "roomCapacity"

// end